server:
  port: 9494
  
spring:
  application:
    name: admin-server
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7761/eureka      
  
  instance:
    hostname: localhost
    prefer-ip-address: true
    
management:
  endpoint:
    health:
      show-details: always 
    shutdown:
      enabled: true  
      
  endpoints:
    web:
      exposure:
        include:
        - "*"      