server:
  port: 7761
  
spring:
  application:
    name: eureka-registry
    
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7761/eureka 
 